<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>APS 240: Data Analysis and Statistics with R</title>
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <meta name="description" content="Course book for Data Analysis and Statistics with R (APS 240) in the Department of Animal and Plant Sciences, University of Sheffield">
  <meta name="generator" content="bookdown 0.1.5 and GitBook 2.6.7">

  <meta property="og:title" content="APS 240: Data Analysis and Statistics with R" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Course book for Data Analysis and Statistics with R (APS 240) in the Department of Animal and Plant Sciences, University of Sheffield" />
  <meta name="github-repo" content="dzchilds/stats-for-bio" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="APS 240: Data Analysis and Statistics with R" />
  
  <meta name="twitter:description" content="Course book for Data Analysis and Statistics with R (APS 240) in the Department of Animal and Plant Sciences, University of Sheffield" />
  

<meta name="author" content="Dylan Z. Childs">

<meta name="date" content="2016-09-28">

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="sampling-error.html">
<link rel="next" href="comparing-populations.html">

<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<style type="text/css">

.warning-box {
  border: 3px solid #e60000;
  margin:  0px 0px 20px 0px;
  padding: 10px 10px 10px 10px;
  border-radius: 6px 6px 6px 6px;
}

.advanced-box {
  border: 3px solid #268bd2;
  margin:  0px 0px 20px 0px;
  padding: 10px 10px 10px 10px;
  border-radius: 6px 6px 6px 6px;
}

.do-something {
  border: 3px solid #803e00;
  margin:  0px 0px 20px 0px;
  padding: 10px 10px 10px 10px;
  border-radius: 6px 6px 6px 6px;
}

</style>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>


  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">APS 240</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Course information and overview</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#why-data-analysis"><i class="fa fa-check"></i><b>1.1</b> Why do a data analysis course?</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#overview"><i class="fa fa-check"></i><b>1.2</b> Course overview</a><ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#aims"><i class="fa fa-check"></i><b>1.2.1</b> Aims</a></li>
<li class="chapter" data-level="1.2.2" data-path="index.html"><a href="index.html#objectives"><i class="fa fa-check"></i><b>1.2.2</b> Objectives</a></li>
<li class="chapter" data-level="1.2.3" data-path="index.html"><a href="index.html#assumed-background"><i class="fa fa-check"></i><b>1.2.3</b> Assumed background</a></li>
<li class="chapter" data-level="1.2.4" data-path="index.html"><a href="index.html#methods"><i class="fa fa-check"></i><b>1.2.4</b> Methods</a></li>
<li class="chapter" data-level="1.2.5" data-path="index.html"><a href="index.html#non-assessed-material"><i class="fa fa-check"></i><b>1.2.5</b> Non-assessed material</a></li>
<li class="chapter" data-level="1.2.6" data-path="index.html"><a href="index.html#what-is-required-of-you"><i class="fa fa-check"></i><b>1.2.6</b> What is required of you?</a></li>
<li class="chapter" data-level="1.2.7" data-path="index.html"><a href="index.html#assessment"><i class="fa fa-check"></i><b>1.2.7</b> Assessment</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#how-to-use-the-teaching-material"><i class="fa fa-check"></i><b>1.3</b> How to use the teaching material</a><ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#printed-material"><i class="fa fa-check"></i><b>1.3.1</b> The online course book</a></li>
<li class="chapter" data-level="1.3.2" data-path="index.html"><a href="index.html#printed-material"><i class="fa fa-check"></i><b>1.3.2</b> Printed material</a></li>
<li class="chapter" data-level="1.3.3" data-path="index.html"><a href="index.html#how-to-make-best-use-of-it"><i class="fa fa-check"></i><b>1.3.3</b> How to make best use of the teaching material</a></li>
<li class="chapter" data-level="1.3.4" data-path="index.html"><a href="index.html#conventions"><i class="fa fa-check"></i><b>1.3.4</b> Conventions used in the course material</a></li>
<li class="chapter" data-level="1.3.5" data-path="index.html"><a href="index.html#feedback"><i class="fa fa-check"></i><b>1.3.5</b> Feedback</a></li>
<li class="chapter" data-level="1.3.6" data-path="index.html"><a href="index.html#help"><i class="fa fa-check"></i><b>1.3.6</b> Help sessions</a></li>
<li class="chapter" data-level="1.3.7" data-path="index.html"><a href="index.html#overall"><i class="fa fa-check"></i><b>1.3.7</b> Overall…</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#health-and-safety"><i class="fa fa-check"></i><b>1.4</b> Health and safety using display screen equipment</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="expected-learning-outcomes.html"><a href="expected-learning-outcomes.html"><i class="fa fa-check"></i><b>2</b> Expected learning outcomes</a><ul>
<li class="chapter" data-level="2.1" data-path="expected-learning-outcomes.html"><a href="expected-learning-outcomes.html#statistical-concepts-i"><i class="fa fa-check"></i><b>2.1</b> Statistical Concepts (I)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="programming-prerequisites.html"><a href="programming-prerequisites.html"><i class="fa fa-check"></i><b>3</b> Programming prerequisites</a><ul>
<li class="chapter" data-level="3.1" data-path="programming-prerequisites.html"><a href="programming-prerequisites.html#starting-an-r-session-in-rstudio"><i class="fa fa-check"></i><b>3.1</b> Starting an R session in RStudio</a></li>
<li class="chapter" data-level="3.2" data-path="programming-prerequisites.html"><a href="programming-prerequisites.html#using-packages"><i class="fa fa-check"></i><b>3.2</b> Using packages</a></li>
<li class="chapter" data-level="3.3" data-path="programming-prerequisites.html"><a href="programming-prerequisites.html#reading-data-into-r"><i class="fa fa-check"></i><b>3.3</b> Reading data into R</a></li>
<li class="chapter" data-level="3.4" data-path="programming-prerequisites.html"><a href="programming-prerequisites.html#data-frames"><i class="fa fa-check"></i><b>3.4</b> Data frames</a></li>
<li class="chapter" data-level="3.5" data-path="programming-prerequisites.html"><a href="programming-prerequisites.html#package-functions"><i class="fa fa-check"></i><b>3.5</b> Package functions</a></li>
</ul></li>
<li class="part"><span><b>Statistical Concepts (I)</b></span></li>
<li class="chapter" data-level="4" data-path="the-scientific-process.html"><a href="the-scientific-process.html"><i class="fa fa-check"></i><b>4</b> The scientific process</a><ul>
<li class="chapter" data-level="4.1" data-path="the-scientific-process.html"><a href="the-scientific-process.html#stages"><i class="fa fa-check"></i><b>4.1</b> Stages in the scientific process</a><ul>
<li class="chapter" data-level="4.1.1" data-path="the-scientific-process.html"><a href="the-scientific-process.html#observations"><i class="fa fa-check"></i><b>4.1.1</b> Observations</a></li>
<li class="chapter" data-level="4.1.2" data-path="the-scientific-process.html"><a href="the-scientific-process.html#questions"><i class="fa fa-check"></i><b>4.1.2</b> Questions</a></li>
<li class="chapter" data-level="4.1.3" data-path="the-scientific-process.html"><a href="the-scientific-process.html#hypotheses"><i class="fa fa-check"></i><b>4.1.3</b> Hypotheses</a></li>
<li class="chapter" data-level="4.1.4" data-path="the-scientific-process.html"><a href="the-scientific-process.html#predictions"><i class="fa fa-check"></i><b>4.1.4</b> Predictions</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="the-scientific-process.html"><a href="the-scientific-process.html#hypothesis-testing"><i class="fa fa-check"></i><b>4.2</b> Hypothesis testing</a></li>
<li class="chapter" data-level="4.3" data-path="the-scientific-process.html"><a href="the-scientific-process.html#are-we-sure"><i class="fa fa-check"></i><b>4.3</b> Don’t we ever know anything for sure?</a></li>
<li class="chapter" data-level="4.4" data-path="the-scientific-process.html"><a href="the-scientific-process.html#further-reading"><i class="fa fa-check"></i><b>4.4</b> Further reading</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-and-variables.html"><a href="data-and-variables.html"><i class="fa fa-check"></i><b>5</b> Data and variables</a><ul>
<li class="chapter" data-level="5.1" data-path="data-and-variables.html"><a href="data-and-variables.html#observations-on-material-and-obvious-things"><i class="fa fa-check"></i><b>5.1</b> “Observations on material and obvious things”</a></li>
<li class="chapter" data-level="5.2" data-path="data-and-variables.html"><a href="data-and-variables.html#var-types"><i class="fa fa-check"></i><b>5.2</b> Revision: Types of variable</a><ul>
<li class="chapter" data-level="5.2.1" data-path="data-and-variables.html"><a href="data-and-variables.html#nominal-categorical-variables"><i class="fa fa-check"></i><b>5.2.1</b> Nominal (categorical) variables</a></li>
<li class="chapter" data-level="5.2.2" data-path="data-and-variables.html"><a href="data-and-variables.html#ordinal-categorical-data"><i class="fa fa-check"></i><b>5.2.2</b> Ordinal (categorical) data</a></li>
<li class="chapter" data-level="5.2.3" data-path="data-and-variables.html"><a href="data-and-variables.html#interval-scale-numeric-variables"><i class="fa fa-check"></i><b>5.2.3</b> Interval scale (numeric) variables</a></li>
<li class="chapter" data-level="5.2.4" data-path="data-and-variables.html"><a href="data-and-variables.html#ratio-scale-numeric-variables"><i class="fa fa-check"></i><b>5.2.4</b> Ratio scale (numeric) variables</a></li>
<li class="chapter" data-level="5.2.5" data-path="data-and-variables.html"><a href="data-and-variables.html#which-is-best"><i class="fa fa-check"></i><b>5.2.5</b> Which is best?</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="data-and-variables.html"><a href="data-and-variables.html#accuracy-precision"><i class="fa fa-check"></i><b>5.3</b> Accuracy and precision</a><ul>
<li class="chapter" data-level="5.3.1" data-path="data-and-variables.html"><a href="data-and-variables.html#what-do-they-mean"><i class="fa fa-check"></i><b>5.3.1</b> What do they mean?</a></li>
<li class="chapter" data-level="5.3.2" data-path="data-and-variables.html"><a href="data-and-variables.html#implied-precision---significant-figures"><i class="fa fa-check"></i><b>5.3.2</b> Implied precision - significant figures</a></li>
<li class="chapter" data-level="5.3.3" data-path="data-and-variables.html"><a href="data-and-variables.html#how-precise-should-measurements-be"><i class="fa fa-check"></i><b>5.3.3</b> How precise should measurements be?</a></li>
<li class="chapter" data-level="5.3.4" data-path="data-and-variables.html"><a href="data-and-variables.html#error-bias-and-prejudice"><i class="fa fa-check"></i><b>5.3.4</b> Error, bias and prejudice</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="learning-from-data.html"><a href="learning-from-data.html"><i class="fa fa-check"></i><b>6</b> Learning from data</a><ul>
<li class="chapter" data-level="6.1" data-path="learning-from-data.html"><a href="learning-from-data.html#populations"><i class="fa fa-check"></i><b>6.1</b> Populations</a></li>
<li class="chapter" data-level="6.2" data-path="learning-from-data.html"><a href="learning-from-data.html#learning-about-populations"><i class="fa fa-check"></i><b>6.2</b> Learning about populations</a></li>
<li class="chapter" data-level="6.3" data-path="learning-from-data.html"><a href="learning-from-data.html#morph-example"><i class="fa fa-check"></i><b>6.3</b> A simple example</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="sampling-error.html"><a href="sampling-error.html"><i class="fa fa-check"></i><b>7</b> Sampling error</a><ul>
<li class="chapter" data-level="7.1" data-path="sampling-error.html"><a href="sampling-error.html#sampling-error-1"><i class="fa fa-check"></i><b>7.1</b> Sampling error</a></li>
<li class="chapter" data-level="7.2" data-path="sampling-error.html"><a href="sampling-error.html#sampling-distributions"><i class="fa fa-check"></i><b>7.2</b> Sampling distributions</a></li>
<li class="chapter" data-level="7.3" data-path="sampling-error.html"><a href="sampling-error.html#the-effect-of-sample-size"><i class="fa fa-check"></i><b>7.3</b> The effect of sample size</a></li>
<li class="chapter" data-level="7.4" data-path="sampling-error.html"><a href="sampling-error.html#the-standard-error"><i class="fa fa-check"></i><b>7.4</b> The standard error</a></li>
<li class="chapter" data-level="7.5" data-path="sampling-error.html"><a href="sampling-error.html#what-is-the-point-of-all-this"><i class="fa fa-check"></i><b>7.5</b> What is the point of all this!?</a></li>
</ul></li>
<li class="part"><span><b>Statistical Concepts (II)</b></span></li>
<li class="chapter" data-level="8" data-path="statistical-significance-and-p-values.html"><a href="statistical-significance-and-p-values.html"><i class="fa fa-check"></i><b>8</b> Statistical significance and <em>p</em>-values</a><ul>
<li class="chapter" data-level="8.1" data-path="statistical-significance-and-p-values.html"><a href="statistical-significance-and-p-values.html#bootstrap"><i class="fa fa-check"></i><b>8.1</b> Estimating a sampling distribution</a><ul>
<li class="chapter" data-level="8.1.1" data-path="statistical-significance-and-p-values.html"><a href="statistical-significance-and-p-values.html#bootstrap-overview"><i class="fa fa-check"></i><b>8.1.1</b> Overviw of bootstrapping</a></li>
<li class="chapter" data-level="8.1.2" data-path="statistical-significance-and-p-values.html"><a href="statistical-significance-and-p-values.html#doing-it-for-real"><i class="fa fa-check"></i><b>8.1.2</b> Doing it for real</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="statistical-significance-and-p-values.html"><a href="statistical-significance-and-p-values.html#statistical-significance"><i class="fa fa-check"></i><b>8.2</b> Statistical significance</a></li>
<li class="chapter" data-level="8.3" data-path="statistical-significance-and-p-values.html"><a href="statistical-significance-and-p-values.html#concluding-words"><i class="fa fa-check"></i><b>8.3</b> Concluding words</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="comparing-populations.html"><a href="comparing-populations.html"><i class="fa fa-check"></i><b>9</b> Comparing populations</a><ul>
<li class="chapter" data-level="9.1" data-path="comparing-populations.html"><a href="comparing-populations.html#making-comparisons"><i class="fa fa-check"></i><b>9.1</b> Making comparisons</a></li>
<li class="chapter" data-level="9.2" data-path="comparing-populations.html"><a href="comparing-populations.html#morph-weights-eg"><i class="fa fa-check"></i><b>9.2</b> A new example</a></li>
<li class="chapter" data-level="9.3" data-path="comparing-populations.html"><a href="comparing-populations.html#evaluating-differences"><i class="fa fa-check"></i><b>9.3</b> Evaluating differences</a><ul>
<li class="chapter" data-level="9.3.1" data-path="comparing-populations.html"><a href="comparing-populations.html#statistical-significance-again"><i class="fa fa-check"></i><b>9.3.1</b> Statistical significance (again)</a></li>
<li class="chapter" data-level="9.3.2" data-path="comparing-populations.html"><a href="comparing-populations.html#a-permutation-test"><i class="fa fa-check"></i><b>9.3.2</b> A permutation test</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="comparing-populations.html"><a href="comparing-populations.html#what-have-we-learned"><i class="fa fa-check"></i><b>9.4</b> What have we learned?</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="concluding-remarks.html"><a href="concluding-remarks.html"><i class="fa fa-check"></i><b>10</b> Concluding remarks</a><ul>
<li class="chapter" data-level="10.1" data-path="concluding-remarks.html"><a href="concluding-remarks.html#a-few-words-about-the-null-hypothesis"><i class="fa fa-check"></i><b>10.1</b> A few words about the null hypothesis</a><ul>
<li class="chapter" data-level="10.1.1" data-path="concluding-remarks.html"><a href="concluding-remarks.html#hypotheses-and-null-hypotheses"><i class="fa fa-check"></i><b>10.1.1</b> Hypotheses and null hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="concluding-remarks.html"><a href="concluding-remarks.html#a-few-words-about-p-values"><i class="fa fa-check"></i><b>10.2</b> A few words about <em>p</em> values</a><ul>
<li class="chapter" data-level="10.2.1" data-path="concluding-remarks.html"><a href="concluding-remarks.html#what-if-is-close-to-0.05"><i class="fa fa-check"></i><b>10.2.1</b> What if is close to 0.05?</a></li>
<li class="chapter" data-level="10.2.2" data-path="concluding-remarks.html"><a href="concluding-remarks.html#biological-vs.statistical-significance"><i class="fa fa-check"></i><b>10.2.2</b> Biological vs. statistical significance</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>Evaluating Associations</b></span></li>
<li class="part"><span><b>Comparing Means</b></span></li>
<li class="part"><span><b>Experimental Design</b></span></li>
<li class="part"><span><b>Miscellaneous Topics</b></span></li>
<li class="appendix"><span><b>Supplementary Material</b></span></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">APS 240: Data Analysis and Statistics with R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statistical-significance-and-p-values" class="section level1">
<h1><span class="header-section-number">Chapter 8</span> Statistical significance and <em>p</em>-values</h1>
<p>We have already pointed out that we use frequentist statistics in this book. While it isn’t possible to give a precise description of how frequentist statistics works in an introductory book, we can at least provide a rough indication. Frequentist statistics works by asking <em>what would have happened</em> if we were to repeat an experiment or data collection exercise many times, <em>assuming that the relevant population parameters remain the same</em> each time. That was the basic idea we employed to generate those sampling distributions in the last chapter.</p>
<p>The choice of population parameter(s) to work with depend on what kind of question we are asking. This obviously varies from one situation to another. The thing that is common to every frequentist technique is that we ultimately have to work out how a sampling distribution of some kind should look. If we can do that, then we can ask, for a given scenario, how likely or unlikely a particular result is. This naturally leads onto two of the most important ideas in this book: statistical significance and <em>p</em>-values. The goal of this chapter is to introduce these ideas.</p>
<div id="bootstrap" class="section level2">
<h2><span class="header-section-number">8.1</span> Estimating a sampling distribution</h2>
<p>Let’s carry on with the plant polymorphism example (yes, again). Our ultimate goal is to evaluate whether the purple morph frequency is greater than 25% in the new study population. The suggestion in the preamble of this chapter is that, to get to this point, we need to work out what the sampling distribution of the purple morph frequency estimate looks like. At first glance this seems like an impossible task. We can’t use simulations, because we don’t know the true frequency of purple morphs in the population. All we have is the one sample.</p>
<p>The solution to this problem is surprisingly simple (or at least the basic idea is simple). Since we don’t know much about the population, we use the sample to approximate some aspect(s) of it, and then work out what the sampling distribution of our estimate should look like using this approximation.</p>
<p>Let’s unpack this idea a bit more, and then try it out for real.</p>
<div id="bootstrap-overview" class="section level3">
<h3><span class="header-section-number">8.1.1</span> Overviw of bootstrapping</h3>
<p>There are many different ways to approximate a population from a sample. One of the simplest methods—for easy problems at least—is to <em>pretend the sample is the true population</em>. Then, all we have to do to get at a sampling distribution is draw new samples from this pretend population. That may sound a lot like cheating, but it turns out that this is a perfectly valid way to construct useful sampling distributions for many kinds of problems.</p>
<p>Here is a how it works for our example, using a physical analogy. Imagine that we only have one sample, and have written down the colour of each sampled individual on a different piece of paper, and then placed all of these bits of paper into in a hat. We then do the following:</p>
<ol style="list-style-type: decimal">
<li>Pick a piece of paper at random, record its value (purple or green), put the paper back into the hat, and shake the hat about to mix up the bits of paper.</li>
</ol>
<p>(The shaking here is meant to ensure that each piece of paper has an equal chance of being picked, i.e. we’re taking a random sample. This might not work in reality, but let’s assume it does.)</p>
<ol start="2" style="list-style-type: decimal">
<li><p>Pick another piece of paper (you might get the same one), record its value, and then put that back into the hat, remembering to shake everything up.</p></li>
<li><p>Repeat this process until we have a recorded new sample of colours which is the same size as your real sample. Now we have a ‘new sample’.</p></li>
</ol>
<p>(This process is called ‘sampling with replacement’. Each artificial sample is called a ‘bootstrapped sample’.)</p>
<ol start="4" style="list-style-type: decimal">
<li><p>For each bootstrapped sample, calculate whatever quantity is of interest. In our example, this is the proportion of purple plants sampled.</p></li>
<li><p>Repeat steps 1-4 until we have generated a large number of bootstrapped samples. About 10000 is often sufficient for many problems.</p></li>
</ol>
<p>Although it may seem like cheating (it’s not!), this process really does produce an approximation of the sampling distribution of the quantity we’re interest in. It is called <strong>bootstrapping</strong> (or ‘the bootstrap’). The bootstrap was invented by a very smart statistician called <a href="https://en.wikipedia.org/wiki/Bradley_Efron">Bradley Efron</a>. We’re introducing it here because it allows you to see how frequentist methodology works without having to do any nasty mathematics. We’re not expecting you to learn it, so don’t worry too much if you find it tricky to understand. It is an odd concept.</p>
</div>
<div id="doing-it-for-real" class="section level3">
<h3><span class="header-section-number">8.1.2</span> Doing it for real</h3>
<p>Let’s assume we’ve sampled 250 individuals from our new plant population. We’re going to use this hypothetical sample to implement the bootstrap in R.</p>
<div class="do-something">
<p>
The best way to understand what follows is to actually work through the example. You’re strongly encouraged to do this…
</p>
</div>
<p>A data set representing this situation is stored in a Comma Seperated Value (CSV) text file called ‘MORPH_DATA.CSV’. Download the file from MOLE and place it in your working directory (you should set this at the beginning of the R session). Next, run through the following steps:</p>
<ul>
<li><p>Read the data into an R data frame using <code>read.csv</code>, assigning the data frame the name <code>morph.data</code>.</p></li>
<li><p>Use a function like <code>glimpse</code> (from <strong>dplyr</strong>) or <code>str</code> (from base R) to inspect the structure of <code>morph.data</code>. How many variables are in the dataset? What are their names? What kind of variables are they?</p></li>
<li><p>Use the <code>View</code> function to inspect the data. Is this what you expected? Are the values of the different variables as you would expect them to be?</p></li>
</ul>
<p>The point of all this is to ‘sanity check’ the data, i.e. to make sure we understand the data and that there are no obvious problems with it. <strong>We should always check our data after we’ve read it in</strong>. There is really no point messing about with the likes of <strong>dplyr</strong> and <strong>ggplot2</strong>, or carrying out a statistical analysis, until we have done this. If we don’t understand how our data is organised, and what variables we are working with, there is very real risk that we will make a lot of avoidable mistakes.</p>
<p>What you should have found is that <code>morph.data</code> contains 250 rows and two columns/variables: <code>Colour</code> and <code>Weight</code>. <code>Colour</code> is a categorical variable (a ‘factor’, in R-land) and <code>Weight</code> is a numeric variable. The <code>Colour</code> variable obviously contains the colour of each plant in the sample. What about <code>Weight</code>? We don’t need this now, but we’ll use it in the next chapter.</p>
<p>Now that we understand the data, we’re ready to implement bootstrapping (using R of course, no hats or paper required). We’re going to introduce a few new R tricks here. We’ll explain them as we go, but if you’re not a huge R fan, there’s really no need to remember them.</p>
<p>We want to construct a sampling distribution for the frequency of purple morphs, so the variable that matters here is <code>Colour</code>. Rather than work with this inside the data frame, we’re going to pull it out using the <code>$</code> operator, assign it a name (<code>plant_morphs</code>), and then take a look at the first 20 values:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">plant_morphs &lt;-<span class="st"> </span>morph.data$Colour
<span class="kw">levels</span>(plant_morphs)</code></pre></div>
<pre><code>## [1] &quot;Green&quot;  &quot;Purple&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(plant_morphs, <span class="dv">100</span>) <span class="co"># just show the first 100 values</span></code></pre></div>
<pre><code>##   [1] Green  Green  Green  Purple Green  Green  Green  Green  Green  Green 
##  [11] Green  Green  Green  Purple Green  Green  Purple Purple Green  Green 
##  [21] Green  Green  Green  Purple Green  Green  Green  Green  Purple Purple
##  [31] Green  Green  Green  Purple Purple Green  Green  Green  Green  Purple
##  [41] Green  Purple Green  Green  Purple Purple Green  Green  Green  Green 
##  [51] Green  Green  Purple Purple Purple Green  Green  Green  Purple Green 
##  [61] Purple Green  Purple Green  Purple Purple Green  Green  Purple Green 
##  [71] Green  Purple Purple Green  Purple Green  Green  Green  Green  Purple
##  [81] Purple Green  Purple Green  Green  Green  Purple Purple Green  Purple
##  [91] Green  Green  Green  Green  Green  Green  Purple Green  Green  Green 
## Levels: Green Purple</code></pre>
<p>Hopefully you followed that—<code>plant_morphs</code> is just a simple vector (a factor, with 2 categories) containing the colour information.</p>
<p>Let’s calculate and store the sample size (<code>samp_size</code>), and the point estimate of purple morph frequency (<code>mean_point_est</code>) from this sample:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">samp_size &lt;-<span class="st"> </span><span class="kw">length</span>(plant_morphs)
samp_size</code></pre></div>
<pre><code>## [1] 250</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mean_point_est &lt;-<span class="st"> </span><span class="dv">100</span> *<span class="st"> </span><span class="kw">sum</span>(plant_morphs ==<span class="st"> &quot;Purple&quot;</span>) /<span class="st"> </span>samp_size
mean_point_est</code></pre></div>
<pre><code>## [1] 30.8</code></pre>
<p>So… 30.8% of plants were purple among our sample of 250 plants.</p>
<p>We are now ready to start bootstrapping! We’ll use 10000 bootstrap samples, and for convenience, we’ll store this number in <code>n_samp</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">n_samp &lt;-<span class="st"> </span><span class="dv">10000</span></code></pre></div>
<p>We need to resample the <code>plant_morphs</code> vector. The <code>sample</code> function will do this for us (<code>replace = TRUE</code> makes it sample with replacement):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">samp &lt;-<span class="st"> </span><span class="kw">sample</span>(plant_morphs, <span class="dt">replace =</span> <span class="ot">TRUE</span>)
<span class="kw">head</span>(samp, <span class="dv">100</span>) <span class="co"># just show the first 100 values</span></code></pre></div>
<pre><code>##   [1] Purple Green  Green  Green  Purple Green  Green  Green  Purple Purple
##  [11] Green  Purple Green  Green  Green  Green  Purple Green  Green  Green 
##  [21] Green  Green  Green  Purple Green  Purple Green  Green  Green  Green 
##  [31] Green  Purple Purple Purple Green  Green  Green  Green  Green  Green 
##  [41] Green  Green  Purple Green  Green  Green  Purple Green  Green  Green 
##  [51] Green  Green  Green  Green  Green  Green  Purple Green  Green  Purple
##  [61] Purple Green  Green  Green  Green  Purple Purple Green  Green  Purple
##  [71] Green  Green  Green  Green  Purple Green  Green  Purple Green  Purple
##  [81] Green  Purple Green  Green  Green  Green  Green  Green  Green  Green 
##  [91] Green  Purple Green  Green  Green  Green  Green  Green  Purple Green 
## Levels: Green Purple</code></pre>
<p>Compare this one bootstrapped sample to the real one. It’s a random sample of the values in the first sample, as expected. We only need one number from this sample, which is the frequency of purple morphs:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">first_bs_freq &lt;-<span class="st"> </span><span class="dv">100</span> *<span class="st"> </span><span class="kw">sum</span>(samp ==<span class="st"> &quot;Purple&quot;</span>) /<span class="st"> </span>samp_size
<span class="kw">head</span>(first_bs_freq, <span class="dv">100</span>) <span class="co"># just show the first 100 values</span></code></pre></div>
<pre><code>## [1] 27.2</code></pre>
<p>That’s one bootstrapped value of purple morph frequency. Simple! We need 10^{4} values though, and we really don’t want to have to keep doing this over an over ‘by hand’ (making <code>second_bs_freq</code>, <code>third_bs_freq</code>, …). That would be very dull…</p>
<p>Luckily, computers are very good at doing repetative tasks like this. Here is some R code that repeats what we just did <code>n_samp</code> times and stores the bootstrapped sample in a vector called <code>boot_out</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">boot_out &lt;-<span class="st"> </span><span class="kw">replicate</span>(n_samp, {
  samp &lt;-<span class="st"> </span><span class="kw">sample</span>(plant_morphs, <span class="dt">replace =</span> <span class="ot">TRUE</span>)
  <span class="dv">100</span> *<span class="st"> </span><span class="kw">sum</span>(samp ==<span class="st"> &quot;Purple&quot;</span>) /<span class="st"> </span>samp_size
})</code></pre></div>
<p>The <code>replicate</code> function does exactly what you might think it does. It replicates an R expression many times (<code>n_samp</code> in this case) and returns the set of results. Remember, you don’t have to understand this R code, but do ask a TA if you want to know more about it.</p>
<p>The end result of the above is that <code>boot_out</code> now contains a bootstrapped sample of frequency estimates. Let’s take a quick look at the first 25 values, rounding each of them to 2 decimal places (we’ll used the pipe <code>%&gt;%</code> to remind you it exists; just keep in mind this won’t work unless you have loaded the <strong>dplyr</strong> package):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(boot_out, <span class="dv">25</span>) %&gt;%<span class="st"> </span><span class="kw">round</span>(<span class="dv">1</span>)</code></pre></div>
<pre><code>##  [1] 26.0 28.0 32.0 26.8 32.8 35.6 31.2 32.4 33.6 30.0 27.6 29.6 30.8 34.0
## [15] 32.4 38.8 31.6 24.4 31.6 28.4 30.0 32.8 32.4 33.6 32.0</code></pre>
<p>These numbers represents different values of the purple morph frequency that we might expect to generate if we repeated the data collection exercise, assuming the observed purple morph frequency really is equal to that of the actual sample. This is a bootstrapped sampling distribution.</p>
<p>We can use this bootstrapped sampling distribution in a number of useful ways. Let’s plot it first get a sense of what it looks like. A histogram is a good choice here because we have a reasonably large number of cases:</p>
<div class="figure" style="text-align: center"><span id="fig:boot-samp-dist"></span>
<img src="stats-for-bio_files/figure-html/boot-samp-dist-1.png" alt="Bootstrapped sampling distribution of purple morph frequency" width="75%" />
<p class="caption">
Figure 8.1: Bootstrapped sampling distribution of purple morph frequency
</p>
</div>
<p>The mean of the sampling distribution looks to be round about 31%, which is fairly close to the sample mean. We can of course calculate this using R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(boot_out) %&gt;%<span class="st"> </span><span class="kw">round</span>(<span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] 30.8</code></pre>
<p>This is essentially the same as the sample estimate we’re working with. This guaranteed to be the case when we construct a large enough sample, because we’re just resampling the data used to estimate the purple morph frequency.</p>
<p>A more useful quantity is the bootstrapped standard error (SE). This is the standard deviation of the sampling distribution, so all we have to do is apply the <code>sd</code> function to the bootstrapped sample:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sd</span>(boot_out) %&gt;%<span class="st"> </span><span class="kw">round</span>(<span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] 2.9</code></pre>
<p>A large SE implies that our sample size was too small to reliably estimate the population mean.</p>
<p>The standard error is a useful quantity in its own right. It is standard practise to summarise the precision of a point estimate by reporting its standard error. Whenever we report a point estimate, we should also report the standard error, like this…</p>
<blockquote>
<p>The frequency purple morph plants (n = 250) was 30.8% (s.e. ± 2.9).</p>
</blockquote>
<p>Notice that we also report the sample size.</p>
</div>
</div>
<div id="statistical-significance" class="section level2">
<h2><span class="header-section-number">8.2</span> Statistical significance</h2>
<p>Now back to the question that motivated all this work. Is the purple morph frequency is greater than 25% in the new study population? We can never answer a question like this definitively from a sample. Instead, we have to carry out some kind of probabalistic assessment. To make this assessment, we’re going to do something that looks rather odd (frequentist statistics <em>is</em> odd to be honest).</p>
<div class="do-something">
<p>
<strong>Don’t panic…</strong>
</p>
<p>
The ideas in this next section are really quite abstract and can difficult to understand. You aren’t expected to understand them straight away, and you certainly won’t be asked to explain them in an assessment.
</p>
</div>
<p>We’re going to make two important assumptions:</p>
<ol style="list-style-type: decimal">
<li><p>Assume that the true value of the purple morph frequency in our new study population is 25%, i.e. we’ll assume the population parameter of interest is the same as that of the original population that motivated this work. To put it another way, we’re assuming there is really no difference between the populations.</p></li>
<li><p>Assume that the sampling distribution we just generated (via bootstrapping) would have been the same if the null hypothesis were true, but for the fact that the mean would be different (it would be equal to 25%). That is, the expected ‘shape’ of the sampling distribution doesn’t change under the null hypothesis.</p></li>
</ol>
<p>That first assumption is an example of something called a <strong>null hypothesis</strong>. It is called this because it is an hypothesis of ‘no effect’ or ‘no difference’. The second assumption is necessary for the reasoning below to be valid. This is often a reasonable assumption (you’ll have to trust us on this one).</p>
<p>Now we ask, if the purple morph frequency in the population is really 25%, what would the corresponding sampling distibution look like? This is called the <strong>null distribution</strong> (we don’t expect you to remember that) because it’s a distribution expected under the null hypothesis. We calculate a bootstrapped sample from this null distribution, using the second assumption, as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">null_dist &lt;-<span class="st"> </span>boot_out -<span class="st"> </span><span class="kw">mean</span>(boot_out) +<span class="st"> </span><span class="dv">25</span></code></pre></div>
<p>All we actually did here was shift the bootstrapped sampling distribution left until the mean is at 25%. Here’s what this null distribution looks:</p>
<div class="figure" style="text-align: center"><span id="fig:boot-samp-dist-25"></span>
<img src="stats-for-bio_files/figure-html/boot-samp-dist-25-1.png" alt="Sampling distribution of purple morph frequency under the null hypothesis" width="75%" />
<p class="caption">
Figure 8.2: Sampling distribution of purple morph frequency under the null hypothesis
</p>
</div>
<p>What does this figure tell us? The red line shows where the point estimate from the true sample lies. It looks like the observed purple morph frequency would be quite unlikely to have arisen through sampling variation if the population frequency is 25%. We can say this because the observed frequency (red line) lies at the end of one ‘tail’ of the sampling distribution. We need to be able to make a more precise statement than this though.</p>
<p>We need to quantify how often the values of the bootstapped null distribution are greater than the value we estimated from the sample. This is easy to do in R:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p_value &lt;-<span class="st"> </span><span class="kw">sum</span>(null_dist &gt;<span class="st"> </span>mean_point_est) /<span class="st"> </span>n_samp
p_value</code></pre></div>
<pre><code>## [1] 0.0265</code></pre>
<p>This number (generally denoted ‘<em>p</em>’) is called a <strong><em>p</em>-value</strong>. We’re going to calculate a lot of <em>p</em>-values in this book. Actually, R will do it for us. We just have to understand what they mean.</p>
<p>What are we supposed to do with the finding <em>p</em> = <code>p_value</code>? This is the probability of obtaining a result equal to, or ‘more extreme’ than, that which was actually observed, <em>assuming that the hypothesis under consideration (a null hypothesis) is true</em>. The null hypothesis is one of no effect (or no difference), and so a low <em>p</em>-value can be interpreted as evidence for an effect being present. That is, the purple morph frequency we observed is fairly unlikely to occur if its population frequency is 25%. In biological terms, we take the low <em>p</em>-value as evidence for a difference in purple morph frequency among the populations.</p>
<p>You may not have realised it, but we just carried out a <strong>significance test</strong> (by calculating a <em>p</em>-value). It took quite a lot of convoluted reasoning to get there though. We meant it when we said frequentist statistics is odd. That rather non-intuitive chain of reasoning, or at least something similar, underlies all the statistical techniques we use in this course. The good news is that we don’t really have to understand the details to use these tools effectively. We just need to understand the relationship between null hypotheses and <em>p</em>-values.</p>
<p>One question remains: How small does a <em>p</em>-value have to be before we are happy to conclude that the effect is probably present? In practise, we do this by applying a threshold, called a <strong>significance level</strong>. If the <em>p</em>-value is less than the chosen significance level we say the result is said to be <strong>statistically significant</strong>. Most often (in biology at least), we use a significance level of <em>p</em>&lt;0.05 (5%). Why? The short answer is that this is just a convention. Nothing more. There is nothing special about this threshold.</p>
<p>We’ll discuss the idea of <em>p</em>-values a bit more in the next two chapters.</p>
</div>
<div id="concluding-words" class="section level2">
<h2><span class="header-section-number">8.3</span> Concluding words</h2>
<p>The bootstrap is a very powerful tool in the right hands, but it is an advanced technique, and can be difficult to apply in complex settings (e.g. analysis of experiments). We will not apply it routinely in this course. Indeed, you are not expected to be able to use it at all. We adopted the technique to help us understand how frequentist ideas are used to decide if an effect (i.e. a difference) is really there or not.</p>
<p>The details vary from one problem to the next, but ultimately, if we are using frequentist ideas we always have to find a way to do the following…</p>
<ol style="list-style-type: decimal">
<li><p>assume that there is actually no ‘effect’ (the <strong>null hypothesis</strong>), where an effect is expressed in terms of one or more population parameters,</p></li>
<li><p>work out what would happen if we were to repeatedly take frequent samples from a population in this hypothetical situation</p></li>
</ol>
<p>(do you see where the word ‘frequentist’ comes from now?)</p>
<ol start="3" style="list-style-type: decimal">
<li>and then calculate a <strong><em>p</em>-value</strong> to evaluate how likely our observation would be under the hypothesis of no effect.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="sampling-error.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="comparing-populations.html" class="navigation navigation-next " aria-label="Next page""><i class="fa fa-angle-right"></i></a>

<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/2_01_significance_p-values.Rmd",
"text": null
},
"download": null,
"toc": {
"collapse": "section"
},
"split_by": "section"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
